//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// revision is 5 digits - way too big for the revision version part, so we moved the first digit to version build part.
[assembly: AssemblyVersion("1.0.8.7189")]
[assembly: AssemblyFileVersion("1.0.8.7189")]
[assembly: AssemblyInformationalVersion("1.0")]
[assembly: SatelliteContractVersion("1.0.8")]


