//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorSteroids.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TorSteroids.Common.Resources.SR", typeof(SR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value must be in range from {1} to {2}..
        /// </summary>
        internal static string ArgumentOutOfRangeExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the string &apos;{0}&apos; may not be 0..
        /// </summary>
        internal static string ArgumentOutOfRangeStringLengthExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeStringLengthExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; may not contain spaces only..
        /// </summary>
        internal static string ArgumentOutOfRangeStringSpacesExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeStringSpacesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} index value must be in range from {1} to {2}..
        /// </summary>
        internal static string IndexOutOfRangeExceptionMessage {
            get {
                return ResourceManager.GetString("IndexOutOfRangeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC2822 date parse failed for input &apos;{1}&apos;: {0}.
        /// </summary>
        internal static string RFC2822GeneralParseDateTimeExceptionMessage {
            get {
                return ResourceManager.GetString("RFC2822GeneralParseDateTimeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Timezone Format: {0}..
        /// </summary>
        internal static string RFC2822InvalidTimezoneFormatExceptionMessage {
            get {
                return ResourceManager.GetString("RFC2822InvalidTimezoneFormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC2822 date regex match succeeds, but parse the groups raised a &apos;{0}&apos; exception for input &apos;{1}&apos;..
        /// </summary>
        internal static string RFC2822ParseGroupsExceptionMessage {
            get {
                return ResourceManager.GetString("RFC2822ParseGroupsExceptionMessage", resourceCulture);
            }
        }
    }
}
